site_name: MySQL Workbench User Guide

nav:
  - Introduction: "index.md"
  - MySQL Workbench Instructions: "SAM_SQL_TASKS.md"
  - Importing A CSV: "SEAN_SQL_TASKS.md"
  - Export/Import Schema: "EMILY_SQL_TASKS.md"
  - Troubleshooting: "Troubleshooting.md"
  - Glossary: "Glossary.md"

# Repository
repo_name: MySQL Workbench User Guide
repo_url: https://github.com/SSollestre/MySQLWorkbenchUserGuide/blob/main/mkdocs.yml

# Copyright
copyright: Copyright &copy; 2023 Sam, Sean, Emily

theme:
  name: material

  features:
  # - navigation.tabs
  - navigation.sections
  - toc.integrate
  - navigation.top
  - search.suggest
  - search.highlight
  # - content.tabs.link
  language: en
  palette:
  - Scheme: default
    toggle: 
      icon: material/weather-night
      name: Switch to dark mode
    primary:
    accent: deep purple
  - scheme: slate
    toggle:
      icon: material/weather-sunny
      name: Switch to light mode
    primary: 
    accent:

markdown_extensions:

  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde



